# Generated by Django 4.2.1 on 2023-06-03 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_rename_user_utilisateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
