# Generated by Django 4.2.1 on 2023-06-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_rename_name_infrastructure_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='type',
            field=models.CharField(choices=[('pc_windows', 'PC Windows'), ('pc_linux', 'PC Linux'), ('desktop_windows', 'Ordinateur de bureau Windows'), ('desktop_linux', 'Ordinateur de bureau Linux'), ('routeur', 'Routeur'), ('serveur', 'Serveur'), ('unite_centrale', 'Unité centrale')], default='pc_windows', max_length=15),
        ),
    ]
