# Generated by Django 4.2.1 on 2023-06-03 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infrastructure', '0003_machine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='modifie_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upates_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
